// DispIDs.h: Defines a DISPID for each COM property and method we're providing.

// ICalendar
// properties
#define DISPID_CAL_APPEARANCE																	1
#define DISPID_CAL_BACKCOLOR																	2
#define DISPID_CAL_BORDERSTYLE																3
#define DISPID_CAL_CALENDARCOUNT															4
#define DISPID_CAL_CALENDARGRIDCELLSELECTED										5
#define DISPID_CAL_CALENDARGRIDCELLTEXT												6
//#define DISPID_CAL_CALENDARID																	7
#define DISPID_CAL_CARETDATE																	DISPID_VALUE
#define DISPID_CAL_CARETDATETEXT															8
#define DISPID_CAL_DISABLEDEVENTS															9
#define DISPID_CAL_DONTREDRAW																	10
#define DISPID_CAL_DRAGSCROLLTIMEBASE													11
#define DISPID_CAL_ENABLED																		DISPID_ENABLED
#define DISPID_CAL_FIRSTDATE																	12
#define DISPID_CAL_FONT																				13
#define DISPID_CAL_FORECOLOR																	14
#define DISPID_CAL_HEADERTEXT																	15
#define DISPID_CAL_HIGHLIGHTTODAYDATE													16
#define DISPID_CAL_HOVERTIME																	17
#define DISPID_CAL_HWND																				18
#define DISPID_CAL_KEEPSELECTIONONNAVIGATION									19
#define DISPID_CAL_LASTDATE																		20
#define DISPID_CAL_MAXDATE																		21
#define DISPID_CAL_MAXSELECTEDDATES														22
#define DISPID_CAL_MINDATE																		23
#define DISPID_CAL_MONTHBACKCOLOR															24
#define DISPID_CAL_MOUSEICON																	25
#define DISPID_CAL_MOUSEPOINTER																26
#define DISPID_CAL_MULTISELECT																27
#define DISPID_CAL_PADDING																		28
#define DISPID_CAL_PROCESSCONTEXTMENUKEYS											29
#define DISPID_CAL_REGISTERFOROLEDRAGDROP											30
#define DISPID_CAL_RIGHTTOLEFT																31
#define DISPID_CAL_SCROLLRATE																	32
#define DISPID_CAL_SHOWTODAYDATE															33
#define DISPID_CAL_SHOWTRAILINGDATES													34
#define DISPID_CAL_SHOWWEEKNUMBERS														35
#define DISPID_CAL_STARTOFWEEK																36
#define DISPID_CAL_SUPPORTOLEDRAGIMAGES												37
#define DISPID_CAL_TITLEBACKCOLOR															38
#define DISPID_CAL_TITLEFORECOLOR															39
#define DISPID_CAL_TODAYDATE																	40
#define DISPID_CAL_TRAILINGFORECOLOR													41
#define DISPID_CAL_USEPADDING																	42
#define DISPID_CAL_USESHORTESTDAYNAMES												43
#define DISPID_CAL_USESYSTEMFONT															44
#define DISPID_CAL_VERSION																		45
#define DISPID_CAL_VIEW																				46
#define DISPID_CAL_DETECTDOUBLECLICKS													58
// fingerprint
#define DISPID_CAL_APPID																			500
#define DISPID_CAL_APPNAME																		501
#define DISPID_CAL_APPSHORTNAME																502
#define DISPID_CAL_BUILD																			503
#define DISPID_CAL_CHARSET																		504
#define DISPID_CAL_ISRELEASE																	505
#define DISPID_CAL_PROGRAMMER																	506
#define DISPID_CAL_TESTER																			507
// methods
#define DISPID_CAL_ABOUT																			DISPID_ABOUTBOX
#define DISPID_CAL_COUNTVISIBLEMONTHS													47
#define DISPID_CAL_GETMAXTODAYWIDTH														48
#define DISPID_CAL_GETMINIMUMSIZE															49
#define DISPID_CAL_GETRECTANGLE																50
#define DISPID_CAL_GETSELECTION																51
#define DISPID_CAL_HITTEST																		52
#define DISPID_CAL_LOADSETTINGSFROMFILE												53
#define DISPID_CAL_MINIMIZERECTANGLE													54
#define DISPID_CAL_REFRESH																		DISPID_REFRESH
#define DISPID_CAL_SAVESETTINGSTOFILE													55
#define DISPID_CAL_SETBOLDDATES																56
#define DISPID_CAL_SETSELECTION																57
#define DISPID_CAL_FINISHOLEDRAGDROP													59


// _ICalendarEvents
// methods
#define DISPID_CALE_CLICK																			1
#define DISPID_CALE_CONTEXTMENU																2
#define DISPID_CALE_DATEMOUSEENTER														3
#define DISPID_CALE_DATEMOUSELEAVE														4
#define DISPID_CALE_DBLCLICK																	5
#define DISPID_CALE_DESTROYEDCONTROLWINDOW										6
#define DISPID_CALE_GETBOLDDATES															7
#define DISPID_CALE_KEYDOWN																		8
#define DISPID_CALE_KEYPRESS																	9
#define DISPID_CALE_KEYUP																			10
#define DISPID_CALE_MCLICK																		11
#define DISPID_CALE_MDBLCLICK																	12
#define DISPID_CALE_MOUSEDOWN																	13
#define DISPID_CALE_MOUSEENTER																14
#define DISPID_CALE_MOUSEHOVER																15
#define DISPID_CALE_MOUSELEAVE																16
#define DISPID_CALE_MOUSEMOVE																	17
#define DISPID_CALE_MOUSEUP																		18
#define DISPID_CALE_OLEDRAGDROP																19
#define DISPID_CALE_OLEDRAGENTER															20
#define DISPID_CALE_OLEDRAGLEAVE															21
#define DISPID_CALE_OLEDRAGMOUSEMOVE													22
#define DISPID_CALE_RCLICK																		23
#define DISPID_CALE_RDBLCLICK																	24
#define DISPID_CALE_RECREATEDCONTROLWINDOW										25
#define DISPID_CALE_RESIZEDCONTROLWINDOW											26
#define DISPID_CALE_SELECTIONCHANGED													27
#define DISPID_CALE_VIEWCHANGED																28
#define DISPID_CALE_MOUSEWHEEL																29
#define DISPID_CALE_XCLICK																		30
#define DISPID_CALE_XDBLCLICK																	31


// IDateTimePicker
// properties
#define DISPID_DTP_ALLOWNULLSELECTION													1
#define DISPID_DTP_APPEARANCE																	2
#define DISPID_DTP_BORDERSTYLE																3
#define DISPID_DTP_CALENDARBACKCOLOR													4
#define DISPID_DTP_CALENDARCARETDATETEXT											5
#define DISPID_DTP_CALENDARDRAGSCROLLTIMEBASE									6
#define DISPID_DTP_CALENDARFIRSTDATE													7
#define DISPID_DTP_CALENDARFONT																8
#define DISPID_DTP_CALENDARFORECOLOR													9
#define DISPID_DTP_CALENDARGRIDCELLSELECTED										10
#define DISPID_DTP_CALENDARGRIDCELLTEXT												11
#define DISPID_DTP_CALENDARHEADERTEXT													12
#define DISPID_DTP_CALENDARHIGHLIGHTTODAYDATE									13
#define DISPID_DTP_CALENDARHOVERTIME													14
#define DISPID_DTP_CALENDARKEEPSELECTIONONNAVIGATION					15
#define DISPID_DTP_CALENDARLASTDATE														16
#define DISPID_DTP_CALENDARMONTHBACKCOLOR											17
#define DISPID_DTP_CALENDARSHOWTODAYDATE											18
#define DISPID_DTP_CALENDARSHOWTRAILINGDATES									19
#define DISPID_DTP_CALENDARSHOWWEEKNUMBERS										20
#define DISPID_DTP_CALENDARTITLEBACKCOLOR											21
#define DISPID_DTP_CALENDARTITLEFORECOLOR											22
#define DISPID_DTP_CALENDARTODAYDATE													23
#define DISPID_DTP_CALENDARTRAILINGFORECOLOR									24
#define DISPID_DTP_CALENDARUSESHORTESTDAYNAMES								25
#define DISPID_DTP_CALENDARUSESYSTEMFONT											26
#define DISPID_DTP_CALENDARVIEW																27
#define DISPID_DTP_CHECKBOXOBJECTSTATE												28
#define DISPID_DTP_CURRENTDATE																DISPID_VALUE
#define DISPID_DTP_CUSTOMDATEFORMAT														29
#define DISPID_DTP_DATEFORMAT																	30
#define DISPID_DTP_DATESELECTED																31
#define DISPID_DTP_DISABLEDEVENTS															32
#define DISPID_DTP_DONTREDRAW																	33
#define DISPID_DTP_DRAGDROPDOWNTIME														34
#define DISPID_DTP_DROPDOWNALIGNMENT													35
#define DISPID_DTP_DROPDOWNBUTTONOBJECTSTATE									36
#define DISPID_DTP_ENABLED																		DISPID_ENABLED
#define DISPID_DTP_FONT																				37
#define DISPID_DTP_HOVERTIME																	38
#define DISPID_DTP_HWND																				39
#define DISPID_DTP_HWNDCALENDAR																40
#define DISPID_DTP_HWNDEDIT																		41
#define DISPID_DTP_HWNDUPDOWN																	42
#define DISPID_DTP_IMEMODE																		43
#define DISPID_DTP_MAXDATE																		44
#define DISPID_DTP_MINDATE																		45
#define DISPID_DTP_MOUSEICON																	46
#define DISPID_DTP_MOUSEPOINTER																47
#define DISPID_DTP_PROCESSCONTEXTMENUKEYS											48
#define DISPID_DTP_REGISTERFOROLEDRAGDROP											49
#define DISPID_DTP_RIGHTTOLEFT																50
#define DISPID_DTP_STARTOFWEEK																51
#define DISPID_DTP_STYLE																			52
#define DISPID_DTP_SUPPORTOLEDRAGIMAGES												53
#define DISPID_DTP_USESYSTEMFONT															54
#define DISPID_DTP_VERSION																		55
#define DISPID_DTP_VALUE																			66
#define DISPID_DTP_DETECTDOUBLECLICKS													67
// fingerprint
#define DISPID_DTP_APPID																			500
#define DISPID_DTP_APPNAME																		501
#define DISPID_DTP_APPSHORTNAME																502
#define DISPID_DTP_BUILD																			503
#define DISPID_DTP_CHARSET																		504
#define DISPID_DTP_ISRELEASE																	505
#define DISPID_DTP_PROGRAMMER																	506
#define DISPID_DTP_TESTER																			507
// methods
#define DISPID_DTP_ABOUT																			DISPID_ABOUTBOX
#define DISPID_DTP_CALENDARGETMAXTODAYWIDTH										56
#define DISPID_DTP_CALENDARGETRECTANGLE												57
#define DISPID_DTP_CLOSEDROPDOWNWINDOW												58
#define DISPID_DTP_GETCHECKBOXRECTANGLE												59
#define DISPID_DTP_GETDROPDOWNBUTTONRECTANGLE									60
#define DISPID_DTP_GETIDEALSIZE																61
#define DISPID_DTP_LOADSETTINGSFROMFILE												62
#define DISPID_DTP_OPENDROPDOWNWINDOW													63
#define DISPID_DTP_REFRESH																		DISPID_REFRESH
#define DISPID_DTP_SAVESETTINGSTOFILE													64
#define DISPID_DTP_SETBOLDDATES																65
#define DISPID_DTP_FINISHOLEDRAGDROP													68


// _IDateTimePickerEvents
// methods
#define DISPID_DTPE_CALENDARCLICK															1
#define DISPID_DTPE_CALENDARCLOSEUP														2
#define DISPID_DTPE_CALENDARCONTEXTMENU												3
#define DISPID_DTPE_CALENDARDATEMOUSEENTER										4
#define DISPID_DTPE_CALENDARDATEMOUSELEAVE										5
//#define DISPID_DTPE_CALENDARDBLCLICK													6
#define DISPID_DTPE_CALENDARDROPDOWN													7
#define DISPID_DTPE_CALENDARKEYDOWN														8
#define DISPID_DTPE_CALENDARKEYPRESS													9
#define DISPID_DTPE_CALENDARKEYUP															10
#define DISPID_DTPE_CALENDARMCLICK														11
//#define DISPID_DTPE_CALENDARMDBLCLICK													12
#define DISPID_DTPE_CALENDARMOUSEDOWN													13
#define DISPID_DTPE_CALENDARMOUSEENTER												14
#define DISPID_DTPE_CALENDARMOUSEHOVER												15
#define DISPID_DTPE_CALENDARMOUSELEAVE												16
#define DISPID_DTPE_CALENDARMOUSEMOVE													17
#define DISPID_DTPE_CALENDARMOUSEUP														18
#define DISPID_DTPE_CALENDAROLEDRAGDROP												19
#define DISPID_DTPE_CALENDAROLEDRAGENTER											20
#define DISPID_DTPE_CALENDAROLEDRAGLEAVE											21
#define DISPID_DTPE_CALENDAROLEDRAGMOUSEMOVE									22
#define DISPID_DTPE_CALENDARRCLICK														23
//#define DISPID_DTPE_CALENDARRDBLCLICK													24
#define DISPID_DTPE_CALENDARVIEWCHANGED												25
#define DISPID_DTPE_CALLBACKFIELDKEYDOWN											26
#define DISPID_DTPE_CLICK																			27
#define DISPID_DTPE_CONTEXTMENU																28
#define DISPID_DTPE_CREATEDCALENDARCONTROLWINDOW							29
#define DISPID_DTPE_CREATEDEDITCONTROLWINDOW									30
#define DISPID_DTPE_CURRENTDATECHANGED												31
#define DISPID_DTPE_DBLCLICK																	32
#define DISPID_DTPE_DESTROYEDCALENDARCONTROLWINDOW						33
#define DISPID_DTPE_DESTROYEDCONTROLWINDOW										34
#define DISPID_DTPE_DESTROYEDEDITCONTROLWINDOW								35
#define DISPID_DTPE_GETBOLDDATES															36
#define DISPID_DTPE_GETCALLBACKFIELDTEXT											37
#define DISPID_DTPE_GETCALLBACKFIELDTEXTSIZE									38
#define DISPID_DTPE_KEYDOWN																		39
#define DISPID_DTPE_KEYPRESS																	40
#define DISPID_DTPE_KEYUP																			41
#define DISPID_DTPE_MCLICK																		42
#define DISPID_DTPE_MDBLCLICK																	43
#define DISPID_DTPE_MOUSEDOWN																	44
#define DISPID_DTPE_MOUSEENTER																45
#define DISPID_DTPE_MOUSEHOVER																46
#define DISPID_DTPE_MOUSELEAVE																47
#define DISPID_DTPE_MOUSEMOVE																	48
#define DISPID_DTPE_MOUSEUP																		49
#define DISPID_DTPE_OLEDRAGDROP																50
#define DISPID_DTPE_OLEDRAGENTER															51
#define DISPID_DTPE_OLEDRAGLEAVE															52
#define DISPID_DTPE_OLEDRAGMOUSEMOVE													53
#define DISPID_DTPE_PARSEUSERINPUT														54
#define DISPID_DTPE_RCLICK																		55
#define DISPID_DTPE_RDBLCLICK																	56
#define DISPID_DTPE_RECREATEDCONTROLWINDOW										57
#define DISPID_DTPE_RESIZEDCONTROLWINDOW											58
#define DISPID_DTPE_CALENDARMOUSEWHEEL												59
#define DISPID_DTPE_CALENDARXCLICK														60
#define DISPID_DTPE_MOUSEWHEEL																61
#define DISPID_DTPE_XCLICK																		62
#define DISPID_DTPE_XDBLCLICK																	63


// IOLEDataObject
// properties
// methods
#define DISPID_ODO_CLEAR																			1
#define DISPID_ODO_GETCANONICALFORMAT													2
#define DISPID_ODO_GETDATA																		3
#define DISPID_ODO_GETFORMAT																	4
#define DISPID_ODO_SETDATA																		5
#define DISPID_ODO_GETDROPDESCRIPTION													6
#define DISPID_ODO_SETDROPDESCRIPTION													7
